version: '3'

services:
  php-apache:
    image: php:8.1-apache
    ports:
      - "8080:80"
    volumes:
      - ./test-ciapp:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: test-ciapp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
